version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./bnbc_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /app
    command: ./entrypoint.sh
  test:
    build: .
    command: python manage.py test
    env_file:
      - .env
    volumes:
      - ./bnbc_api:/app
    depends_on:
      - db

volumes:
  postgres-data:
