# Generated by Django 5.0.7 on 2024-07-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='road',
            name='city',
        ),
        migrations.AddField(
            model_name='household',
            name='city',
            field=models.CharField(default='Tattooine', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='country',
            field=models.CharField(default='Narnia', max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='road',
            field=models.CharField(default='closet', max_length=150, verbose_name='Road'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
