openapi: 3.0.3
info:
  title: BNBC API TEST
  version: 0.0.0
paths:
  /households/:
    get:
      operationId: households_list
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - households
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedHouseholdList'
          description: ''
    post:
      operationId: households_create
      description: API endpoint that allows users to be viewed or edited
      tags:
      - households
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Household'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Household'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Household'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
  /households/{id}/:
    get:
      operationId: households_retrieve
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this household.
        required: true
      tags:
      - households
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
    put:
      operationId: households_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this household.
        required: true
      tags:
      - households
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Household'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Household'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Household'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
    patch:
      operationId: households_partial_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this household.
        required: true
      tags:
      - households
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
    delete:
      operationId: households_destroy
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this household.
        required: true
      tags:
      - households
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /users/:
    get:
      operationId: users_list
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
    post:
      operationId: users_create
      description: API endpoint that allows users to be viewed or edited
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /users/{id}/:
    get:
      operationId: users_retrieve
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: users_partial_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: users_destroy
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /users/{id}/households/:
    get:
      operationId: users_households_retrieve
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: users_households_create
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Household'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Household'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Household'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
    delete:
      operationId: users_households_destroy
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /users/{id}/households/{household_pk}/:
    put:
      operationId: users_households_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: household_pk
        schema:
          type: string
          pattern: ^\d+$
        required: true
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Household'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Household'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Household'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
    patch:
      operationId: users_households_partial_update
      description: API endpoint that allows users to be viewed or edited
      parameters:
      - in: path
        name: household_pk
        schema:
          type: string
          pattern: ^\d+$
        required: true
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedHousehold'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
          description: ''
components:
  schemas:
    Household:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        identifier:
          type: string
          maxLength: 150
        country:
          type: string
          maxLength: 50
        city:
          type: string
          maxLength: 50
        road:
          type: string
          maxLength: 150
        user:
          type: integer
      required:
      - city
      - country
      - id
      - identifier
      - road
      - user
    PaginatedHouseholdList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Household'
    PaginatedUserList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PatchedHousehold:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        identifier:
          type: string
          maxLength: 150
        country:
          type: string
          maxLength: 50
        city:
          type: string
          maxLength: 50
        road:
          type: string
          maxLength: 150
        user:
          type: integer
    PatchedUser:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        households:
          type: string
          readOnly: true
    User:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        households:
          type: string
          readOnly: true
      required:
      - households
      - url
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
